/*****************************************************************************
* Project: RooFit *
* *
* This code was autogenerated by RooClassFactory *
*****************************************************************************/
#ifndef ROODOUBLECB
#define ROODOUBLECB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooRealVar;
class RooAbsReal;

class RooDoubleCB : public RooAbsPdf {
public:
RooDoubleCB() {} ;
RooDoubleCB(const char *name, const char *title,
RooAbsReal& _x,
RooAbsReal& _mean,
RooAbsReal& _sigma,
RooAbsReal& _alpha1,
RooAbsReal& _n1,
RooAbsReal& _alpha2,
RooAbsReal& _n2);
RooDoubleCB(const RooDoubleCB& other, const char* name=0) ;
virtual TObject* clone(const char* newname) const { return new RooDoubleCB(*this,newname); }
inline virtual ~RooDoubleCB() { }
protected:
RooRealProxy x ;
RooRealProxy mean ;
RooRealProxy sigma ;
RooRealProxy alpha1 ;
RooRealProxy n1 ;
RooRealProxy alpha2 ;
RooRealProxy n2 ;
Double_t evaluate() const ;

private:
 ClassDef(RooDoubleCB,1) // Your description goes here...
};

#endif
